### ISSUE TITLE
crash yt.rexx/Odyssey YouTube Streaming

### ISSUE THREAD

**Issue by Maijestro** [smarkusg/mplayer#2]
There are problems with the new Mplayer 1.5 version and YT.rexx/Odyssey when streaming YouTube.

You can reproduce it with the output wpa/comp/sdl_502 and Yt.rexx/Odyssey the script settings look like this:

V2.0 /* Please don't change the formatting */

Embed="0" /* Request content as an embedded video by default? 0/1 */
HTML="0" /* Generate HTML page and open browser? 0/1 */
Login="0" /* Login to your YouTube account? 0/1 */
Debug="1" /* Write debug output to T:YT-Debug.log? 0/1 */
AutoPlay="0" /* Automatically stream videos in mplayer/ffplay? 0/1 */
SkipDASH="0" /* Skip processing of DASH links. 0/1 */
Captions="1" /* Display list of captions? Console mode only. 0/1 */
CapLang="" /* Caption language for autoplay. Blank for none. See docs. */
CapTrans="" /* Translate captions to this language. See docs. */
Browser="" /* Default browser: Odyssey/IBrowse/AWeb/NetSurf. */
ScanLimit="10" /* Maximum amount of video links to scan. */
UsePipe="0" /* Streams HTTPS to MPlayer via STDOUT/STDIN */

TagOrder="18 5 93 32" 22 HD /* 720p/360p/240p / Live 360p/240p */
;PathMP="Workbench:Utilities/MickJT-MPlayer/mplayer-altivec" /* Full path to MPlayer executable */
PathMP="Workbench:Utilities/MPlayer/mplayer-altivec" /* Full path to MPlayer executable */
PathFP="APPDIR:ffplay" /* Full path to FFplay executable */
ArgsMP="-quiet -really-quiet -vo sdl_sm502 -autosync 30 %u -cache 4096" /* Optional parameters for mplayer */
;ArgsMP="-quiet -really-quiet -vo wpa -autosync 35 %u -cache 4096"
ArgsFP="-loglevel quiet -infbuf -skip_loop_filter all -skip_frame noref"
                                         /* Optional parameters for ffplay */

Emotion="0" /* For OLD versions of Emotion. Use APPDIR:Emotion with PIPE: */
              /* Otherwise, set PathMP to Emotion and leave ArgsMP blank. */

AmigaOs4.1 Crash Log: https://paste.ofcode.org/HZ2mrSihNwffPMzGQkDrUr

**Comment by smarkusg** [comment]
If you have the opportunity check the versions on openssl.
No one has previously reported problems with amissl

https://we.tl/t-DRr4MTCCLj

**Comment by Maijestro** [comment]
There is no OpenSSL under AmigaOs4.1, only AmiSSL. And yes, I have checked and my system is always up to date.On real hardware x1000/5000 the native output of Odyssey Youtube is used for videos, but sam460/Pegasos2/AmigaOneXe if they are still in use yt.rexx is used and also for us Qemu users since we have no hardware acceleration.I've added the bug to the github bug tracker. It's not a problem at first, the focus should be on the fact that it works on real machines. So no problem Marek ;-)--- Ursprüngliche Nachricht ---Von: smarkusg
***@***.***>Datum: 25.12.2023 22:48:09An: smarkusg/mplayer ***@***.***>Betreff: Re: [smarkusg/mplayer] crash yt.rexx/Odyssey YouTube Streaming (Issue  #2)
If you have the opportunity check the versions on openssl.
No one has previously reported problems with amissl
https://we.tl/t-DRr4MTCCLj

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @github.com>



[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/smarkusg/mplayer/issues/2#issuecomment-1869127315",
"url": "https://github.com/smarkusg/mplayer/issues/2#issuecomment-1869127315",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]


Versendet mit Emailn.de - Freemail

* Unbegrenzt Speicherplatz
* Eigenes Online-Büro
* 24h besten Mailempfang
* Spamschutz, Adressbuch

**Comment by smarkusg** [comment]
@Rene

The problem also occurs on a real machine.
This will be corrected in the next release.

**Comment by samo790** [comment]
@smarkusg 
The link https://we.tl/t-DRr4MTCCLj is broken

**Comment by smarkusg** [comment]
I have added the Mplayer RC2 update as a HotFix package.
